commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path("create", views.create_listing, name='create_listing'),
    path("<int:auction_id>", views.listing_details, name='details'),
    path("watchlist/toggle/<int:item_id>/", views.toggle_watchlist, name='toggle_watchlist'),
    path("watchlist/", views.view_watchlist, name='watchlist'),
    path("categories/", views.view_categories, name='categories'),
    path("categories/<int:category_id>", views.view_category, name='category'),
    path('create_comment/<int:auction_id>', views.create_comment, name='create_comment'),
    path('delete_comment/<int:auction_id>/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('edit_comment/<int:auction_id>/<int:comment_id>', views.edit_comment, name='edit_comment'),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="auctions/media/default_profile_pic.png")


class Category(models.Model):
    name = models.CharField(max_length=100, blank=True)

    def __str__(self): 
        return self.name


class Auction(models.Model):
    title = models.CharField(max_length=250, blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image_url = models.CharField(max_length=250)
    description = models.TextField(max_length=500, blank=True, default="")
    starting_bid = models.IntegerField(blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self): 
        return f"{self.title}"
    

class Bid(models.Model):
    auction =models.ForeignKey(Auction, on_delete=models.CASCADE, default=None)
    amount = models.CharField(max_length=9)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    
    def __str__(self): 
        return f"${self.amount} for {self.auction.title} by {self.user} on {self.date}"


class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name='comments')
    comment = models.TextField(max_length=500, default=False)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user} for {self.auction.title}"
    
class Watchlist(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    item = models.ForeignKey(Auction, on_delete=models.CASCADE, default=None)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.item.title

commerce/auctions/forms.py
from django.forms import ModelForm
from .models import Auction, Bid, Comment


class AuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = ['title', 'category', 'image_url', 'starting_bid', 'description']

commerce/auctions/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Category, CustomUser, Auction, Bid, Comment, Watchlist
from .forms import AuctionForm

# Create your views here.

def index(request):
    auctions = Auction.objects.all()

    return render(request, "auctions/index.html", {"auctions": auctions})

def listing_details(request, auction_id):
    listing = Auction.objects.get(id=auction_id)
    comments = listing.comments.all()

    return render(request, "auctions/details.html", {"auction": listing, "comments": comments})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = CustomUser.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")
    
@login_required
def create_listing(request):
    template_name = 'auctions/create_listing.html'

    if request.method == 'GET':
        form = AuctionForm()
        return render(request, template_name, {'form': form})

    if request.method == 'POST':
        form = AuctionForm(request.POST)

        if form.is_valid():
            listing = form.save(commit=False)
            listing.save()
            return redirect('auctions:index')

        return render(request, template_name, {'form': form})

@login_required
def toggle_watchlist(request, item_id):
    user = request.user
    item = get_object_or_404(Auction, id=item_id)

    try:
        watchlist = Watchlist.objects.get(user=user, item=item)
        if request.method == "POST":
            watchlist.delete()
            messages.success(request, "Item removed from your watchlist.")
        else:
            messages.warning(request, "Item is already in your watchlist.")
    except Watchlist.DoesNotExist:
        Watchlist.objects.create(user=user, item=item)
        messages.warning(request, "Item added to your watchlist.")

    return redirect('auctions:watchlist')
    
def view_watchlist(request):
    user = request.user
    watchlist = Watchlist.objects.filter(user=user)
    context = {
        'watchlist': watchlist,
        'messages': messages.get_messages(request),
    }

    return render(request, 'auctions/watchlist.html', context)

def view_categories(request):
    categories = Category.objects.all()
    context = {
        'categories' : categories
    }

    return render(request, 'auctions/categories.html', context)

def view_category(request, category_id):
    category = Category.objects.get(id=category_id)
    if category != '':
        listings = Auction.objects.filter(category=category)
        context = {
            'category': category,
            'listings': listings,
        }
    else:
        context = {
            'category': "No auctions for this category for now"
        }
    return render(request, 'auctions/category.html', context)

# CREATE DELETE EDIT Comment
def create_comment(request, auction_id):
    auction = Auction.objects.get(id=auction_id)
    if request.method == 'POST':
        user = request.user
        comment = request.POST.get('comment')
        if comment:
            Comment.objects.create(user=user, auction=auction, comment=comment)
            return redirect('auctions:details', auction_id=auction_id)
    return render(request, 'auctions/details.html', {'auction': auction})

def delete_comment(request, auction_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.user == comment.user:
        comment.delete()
    return redirect('auctions:details', auction_id=auction_id)

def edit_comment(request, auction_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    auction = Auction.objects.get(id=auction_id)

    if request.user == comment.user:
        if request.method == 'POST':
            comment.comment = request.POST.get('comment')
            comment.save()
            return redirect('auctions:details', auction_id = auction_id)
    return render(request, 'auctions/edit_comment.html', {'comment': comment, 'auction': auction})

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
    <ul>
        {% for category in categories %}
        <li> <a href="{% url 'auctions:category' category.pk %}"> <h2 style="width: 30%;" class="btn btn-info btn-lg px-5">{{ category }}</h2> </a></li>
        {% endfor %}
    </ul>
{% endblock %}

commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
    <h1>Active Listings</h1>
    {% if listings %}
        {% for listing in listings  %}
            <a href="{% url 'auctions:details' listing.id %}">
                <div class="column-item col-lg-4 btn-light btn-lg mt-2">
                    <h2 class="btn-secondary btn-lg mb-2 mt-3 text-center">{{ listing.title }}</h2>
                    <img style="width:250px" src="{{ listing.image_url }}" alt="item_img">
                    <p>{{ listing.description }}</p>
                    <p style="font-style: italic;">{{ listing.date }}</p>
                    <h4 class="btn btn-secondary btn-lg px-5">${{ listing.starting_bid }}</h4>
                </div>
            </a>
            
            
        {% endfor %}
    {% else %}
        <h4>No items for an auction...</h4>
    {% endif %}
    
{% endblock %}

commerce/auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
<form method="post" action="{% url 'auctions:create_listing' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Listing">
</form>
    
{% endblock %}

commerce/auctions/templates/auctions/details.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
    <div class="container">
        <h1>Listing: {{ auction.title }}</h1>
        <img style="width:300px" src="{{ auction.image_url }}" alt="">
        <p>{{ auction.description }}</p>
        <h2>${{ auction.starting_bid }}</h2>
        <textarea name="" id="textarea-details" cols="100" rows="1" placeholder="Bid"></textarea>
        <br>
        <button type="submit" class="btn btn-primary">Place Bid</button>
        <br>
        <h3>Details</h3>
        <ul>
            <li>Listed by: </li>
            <li>Category: {{ auction.category }}</li>
        </ul>
        <a href="{% url 'auctions:toggle_watchlist' auction.id %}"><p class="btn btn-secondary">Add to Watchlist</p></a>

        <center>
            <form method="post" action="{% url 'auctions:create_comment' auction.id %}">
                {% csrf_token %}
                <textarea name="comment" id="comment" cols="100" rows="6"></textarea>
                <br>
                <input type="submit" value="Add Comment" class="btn btn-primary">
            </form>
        </center>
        {% if comments %}
            <h4>Comments</h4><hr>
            {% for comment in comments %}
                <div class="row mb-3">
                    <div class="col-8">
                        <p style="word-wrap: break-word;">{{ comment.comment }}</p>
                        <b>Author: @{{ comment.user.username }}</b><span class="fw-lighter"> on {{ comment.date }}</span>
                        {% if comment.user == request.user %}
                            <a href="{% url 'auctions:edit_comment' auction.id comment.id %}" class="btn btn-dark"><i class="bi bi-pen">edit</i></a>
                            <a href="{% url 'auctions:delete_comment' auction.id comment.id %}" class="btn btn-dark"><i class="bi bi-trash">trash</i></a>
                        {% endif %}
                    </div>
                </div>
                <hr>
            {% endfor %}
        {% else %}
                <hr>
            <h4><span class="text-secondary">No reviews yet...</span></h4>
        {% endif %}

    </div>
    
{% endblock %}

commerce/auctions/templates/auctions/edit_comment.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
    <h1>Edit Comment</h1>
    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'auctions:edit_comment' auction.id comment.id %}">
                {% csrf_token %}
                <textarea name="comment" id="" cols="140" rows="6">{{ comment.comment }}</textarea>
                <br>
                <button class="btn btn-outline-success">Save</button>
            </form>
        </div>
    </div>
    
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
    <h1>Active Listings</h1>
    {% if auctions %}
        {% for auction in auctions  %}
            <a href="{% url 'auctions:details' auction.id %}">
                <div class="column-item col-lg-6 btn-light btn-lg mt-2">
                    <h2 class="btn-secondary btn-lg mb-2 mt-3 text-center">{{ auction.title }}</h2>
                    <img style="width:250px" src="{{ auction.image_url }}" alt="item_img">
                    <p>{{ auction.description }}</p>
                    <p style="font-style: italic;">{{ auction.date }}</p>
                    <h4 class="btn btn-secondary btn-lg px-5">${{ auction.starting_bid }}</h4>
                </div>
            </a>
            
            
        {% endfor %}
    {% else %}
        <h4>No items for an auction...</h4>
    {% endif %}
    
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                <span class="btn btn-dark"> Signed in as <strong>{{ user.username }}</strong>.</span>
            {% else %}
                <span class="btn btn-dark">Not signed in.</span>
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create_listing' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        <div class="container">
            {% if messages %}
            <div class="mt-4">
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block body %}
    
<div class="row-lg-5 row-sm-2 btn bg-light text-center">
    {% for item in watchlist %}
    <div class="col-lg-5 mx-2 my-2 watchlist-div" style="border: 1px solid black">
        <h2>{{ item.item.title }}</h2>
        <img style="width: 150px; height: 200px;" src="{{ item.item.image_url }}" alt="">
        <p>Added at {{ item.added_at }}</p>
        <p>Price: ${{ item.item.starting_bid }}</p>
        <form action="{% url 'auctions:toggle_watchlist' item.item.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn text-outline-light btn-outline-danger mb-2">Remove</button>
          </form>
    </div>
    {% endfor %}
</div>
{% endblock %}