wikipedia-clone/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path('', views.index, name="index"),
    path('wiki/<str:TITLE>', views.get_title, name='get_title'),
    path('search', views.search_results, name='search_results'),
    path('new_page', views.create_entry, name='create_entry'),
    path('edit_entry/<str:title>', views.edit_entry, name='edit_entry'),
    path('random_entry/', views.random, name='random')
]

wikipedia-clone/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wikipedia-clone/encyclopedia/models.py
from django.db import models

# Create your models here.

wikipedia-clone/encyclopedia/views.py
from django.shortcuts import render, redirect
from random import choice

from . import util
from markdown import markdown


def index(request):
    entries = util.list_entries()
    return render(request, "encyclopedia/index.html", {
        "entries": entries
    })

def get_title(request, TITLE):
    content = util.get_entry(TITLE)
    return render(request, "encyclopedia/title.html", {
        "content": markdown(content),
        "title": TITLE
    })

def search_results(request):
    entries = util.list_entries()
    query = request.GET.get('q')
    
    if query:
        results = list(filter(lambda x: query.capitalize() in x or query.upper() in x , entries))

    return render(request, 'encyclopedia/search_result.html', {'entries': results})
        
def create_entry(request):
    entries = util.list_entries()

    if request.method == "POST":
        new_entry_title = request.POST.get('title')
        new_entry_content = request.POST.get('content')

        if new_entry_title not in entries and new_entry_title != '':
            util.save_entry(new_entry_title, new_entry_content)
            
            return redirect("encyclopedia:index")

        else:
            error_message = f"The entry with <{new_entry_title}> already exists!>"
            return render(request, 'encyclopedia/create_entry.html', {'error_message': [error_message]})
            
    return render(request, 'encyclopedia/create_entry.html')

def edit_entry(request, title):
     content = util.get_entry(title)

     if request.method == "POST":
        edited_content = request.POST.get('edited_content')

        if edited_content != '':
            util.save_entry(title, edited_content)
            return redirect("encyclopedia:index")

        else:
            return render(request, 'encyclopedia/edit.html', {"content": edited_content, "title":title})
        
     return render(request, 'encyclopedia/edit.html', {"content": content, "title":title})

def random(request):
    entries = util.list_entries()
    random_title = choice(entries)

    content = util.get_entry(random_title)

    return render(request, 'encyclopedia/random.html', {"content": markdown(content), "title": random_title}) 

    

wikipedia-clone/encyclopedia/templates/encyclopedia/create_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create New Entry</h1>

    {% if error_message %}
        {% for i in error_message %}
            <h3 class="btn btn-lg btn-warning">{{ i }}</h3>
        {% endfor %}
    {% endif %}

    <form action="{% url 'encyclopedia:create_entry' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <textarea class='title_textarea' name="title" id="title" cols="80" rows="1" placeholder="Title" value="{{ request.POST.title }}"></textarea>
        <br>
        <textarea name="content" id="content" cols="80" rows="12" placeholder="Your content goes here..." value="{{ request.POST.content }}"></textarea>
        <br>
        <button class="btn btn-success btn-lg px-5" type="submit">Post</button>
    </form>

{% endblock %}

wikipedia-clone/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}


{% block body %}
    <h1>>>{{ title }}</h1>
    <form method="POST">
        {% csrf_token %}

        <textarea name="edited_content" id="" cols="30" rows="10">{{ content }}</textarea>
        <br>
        <button class="btn btn-outline-primary btn-lg" type="submit">Save</button>
    </form>
    
{% endblock %}

wikipedia-clone/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% load static %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    {% if entries %}
    <ul>
        {% for entry in entries %}
            <li> <a href="{% url 'encyclopedia:get_title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
        <h1>NO Content</h1>

    {% endif %}

{% endblock %}

wikipedia-clone/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="get" action="{% url 'encyclopedia:search_results' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" value="{{ request.GET.q }}">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                   <a href="{% url 'encyclopedia:create_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wikipedia-clone/encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}


{% block body %}
        <h1>>>{{ title }}</h1>
        <p>{{ content | safe }}</p>
        <a href="{% url 'encyclopedia:edit_entry' title %}">
            <button class="btn btn-dark btn-lg" type="button">edit</button>
        </a>
        
{% endblock %}

wikipedia-clone/encyclopedia/templates/encyclopedia/search_result.html
{% extends "encyclopedia/layout.html" %}


{% block body %}
    {% if entries %}
    <h1>Search Results:</h1>
        {% for entry in entries %}
            <h4>>> <a href="{% url 'encyclopedia:get_title' entry %}">{{ entry }}</a></h4>
        {% endfor %}
    {% else %}
        <h3 style="color:orange">Not Found!</h3>
    {% endif %}
{% endblock %}

wikipedia-clone/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}


{% block body %}
    {% if content != '' %}
        <p>{{ content | safe }}</p>
        <a href="{% url 'encyclopedia:edit_entry' title %}">
            <button class="btn btn-dark btn-lg" type="button">edit</button>
        </a>
        
    {% else %}
        <h2>No Content with <strong>"{{ title }}"</strong>title!</h2>
    {% endif %}
{% endblock %}